SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS B
JOIN USED_GOODS_BOARD AS A
ON B.USER_ID=A.WRITER_ID
WHERE A.STATUS='DONE'
GROUP BY B.USER_ID
HAVING TOTAL_SALES>=700000
ORDER BY TOTAL_SALES ASC