SELECT
    P.PRODUCT_CODE,
    P.PRICE*SUM(O.SALES_AMOUNT) AS SALES
FROM 
    PRODUCT P
INNER JOIN 
    OFFLINE_SALE O
ON 
    O.PRODUCT_ID=P.PRODUCT_ID
GROUP BY
    P.PRODUCT_CODE
ORDER BY
    SALES DESC,
    P.PRODUCT_CODE ASC